//#define MAX_CLUSTERS_PER_SECTION 64
//#define MAX_TRIANGLES_PER_CLUSTER 128
//#define MAX_VERTEX_PER_CLUSTER 64

//#define MS_GROUP_SIZE				MAX_TRIANGLES_PER_CLUSTER


// Multiwave AS:
//#define MAX_CLUSTERS_PER_AS_GROUP	1024
//#define SECTIONS_PER_AS_GROUP		(MAX_CLUSTERS_PER_AS_GROUP / MAX_CLUSTERS_PER_SECTION)
//#define MAX_SECTIONS_PER_AS_GROUP	SECTIONS_PER_AS_GROUP // TODO: ... (this will be different for preindexed case)

//#define SCENE_GEOMETRY_AS_GROUP_SIZE 128
